/* Thông tin thuốc — biên soạn nội bộ khoa Dược, Bệnh viện Đại học Phenikaa.
   KHÔNG phải văn bản đã ban hành. Tệp do màn hình Biên tập sinh ra. */

const DATA_VERSION = "2026-08-15";

/* Link sang ứng dụng Liều kháng sinh. Sửa nếu tên kho GitHub khác. */
const LINK_LIEU = "https://phenikaamecdls-code.github.io/lieu-khang-sinh/";

const INFO = [
 {
  "ten": "Doxycyclin",
  "cls": "Tetracyclin",
  "nhom": "Nhóm Tetracyclin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Tigecyclin",
  "cls": "Tetracyclin",
  "nhom": "Nhóm Tetracyclin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Ampicillin",
  "cls": "Penicillin",
  "nhom": "Nhóm Penicillin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Ampicillin/Sulbactam",
  "cls": "Penicillin",
  "nhom": "Nhóm Penicillin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Amoxicillin",
  "cls": "Penicillin",
  "nhom": "Nhóm Penicillin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Amoxicillin/Clavulanate",
  "cls": "Penicillin",
  "nhom": "Nhóm Penicillin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Cloxacillin",
  "cls": "Penicillin",
  "nhom": "Nhóm Penicillin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Ticarcillin/Clavulanate",
  "cls": "Penicillin",
  "nhom": "Nhóm Penicillin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Piperacillin/Tazobactam",
  "cls": "Penicillin",
  "nhom": "Nhóm Penicillin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Cefalexin",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 1",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Cefazolin",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 1",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Cefoxitin",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 2",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Cefuroxim",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 2",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Cefaclor",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 2",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Cefprozil",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 2",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Cefotaxim",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Ceftazidim",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Ceftriaxon",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Cefixim",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Cefoperazon",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Cefoperazon/Sulbactam",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Cefpodoxim",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Ceftibuten",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Cefdinir",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Cefditoren",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Ceftazidim/Avibactam",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Cefepim",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 4",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Ceftolozan/Tazobactam",
  "cls": "Cephalosporin",
  "nhom": "Cephalosporin thế hệ 5",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Aztreonam",
  "cls": "Monobactam",
  "nhom": "Nhóm Monobactams",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Meropenem",
  "cls": "Carbapenem",
  "nhom": "Nhóm Carbapenem",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Imipenem/Cilastatin",
  "cls": "Carbapenem",
  "nhom": "Nhóm Carbapenem",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Ertapenem",
  "cls": "Carbapenem",
  "nhom": "Nhóm Carbapenem",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Doripenem",
  "cls": "Carbapenem",
  "nhom": "Nhóm Carbapenem",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Sulfamethoxazol/Trimethoprim",
  "cls": "Sulfonamid",
  "nhom": "Nhóm Sulfonamid và trimethoprim",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Azithromycin",
  "cls": "Macrolid",
  "nhom": "Nhóm Macrolid",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Clindamycin",
  "cls": "Macrolid",
  "nhom": "Nhóm Macrolid",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Clarithromycin",
  "cls": "Macrolid",
  "nhom": "Nhóm Macrolid",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Tobramycin",
  "cls": "Aminoglycosid",
  "nhom": "Nhóm Aminoglycosid",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Gentamycin",
  "cls": "Aminoglycosid",
  "nhom": "Nhóm Aminoglycosid",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Amikacin",
  "cls": "Aminoglycosid",
  "nhom": "Nhóm Aminoglycosid",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Ofloxacin",
  "cls": "Quinolon",
  "nhom": "Nhóm Quinolon",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Norfloxacin",
  "cls": "Quinolon",
  "nhom": "Nhóm Quinolon",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Ciprofloxacin",
  "cls": "Quinolon",
  "nhom": "Nhóm Quinolon",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Levofloxacin",
  "cls": "Quinolon",
  "nhom": "Nhóm Quinolon",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Moxifloxacin",
  "cls": "Quinolon",
  "nhom": "Nhóm Quinolon",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Vancomycin",
  "cls": "Kháng khuẩn khác",
  "nhom": "Nhóm thuốc kháng khuẩn khác",
  "coche": "Kháng sinh glycopeptid thế hệ 1, có tác dụng diệt khuẩn. Thuốc gắn vào đầu tận D-alanyl-D-alanin của các tiểu đơn vị peptid trong quá trình tạo peptidoglycan, qua đó chặn tổng hợp vách tế bào vi khuẩn; ngoài ra còn ức chế tổng hợp RNA của vi khuẩn.\nDo đích tác dụng khác với beta-lactam nên không xảy ra kháng chéo giữa hai nhóm.",
  "chidinh": "Phổ tác dụng giới hạn ở vi khuẩn Gram dương: S. aureus kể cả chủng kháng methicillin, S. epidermidis, liên cầu, cầu khuẩn ruột, phần lớn Actinomyces và Clostridium.\n\nĐường tĩnh mạch — nhiễm khuẩn nặng nghi ngờ hoặc xác định do Gram dương kháng methicillin: nhiễm khuẩn huyết, viêm nội tâm mạc, nhiễm khuẩn da và mô mềm, xương khớp, viêm phổi, viêm màng não.\n\nĐường uống — chỉ dùng cho viêm đại tràng giả mạc và tiêu chảy do Clostridioides difficile, vì thuốc gần như không hấp thu qua đường tiêu hoá. Không dùng đường uống để điều trị nhiễm khuẩn toàn thân.",
  "chongchidinh": "",
  "gan": "Vancomycin thải trừ chủ yếu qua thận ở dạng không đổi, nên các tài liệu tham khảo không đưa ra khuyến cáo hiệu chỉnh liều theo mức độ suy gan.\nVẫn cần theo dõi định kỳ chức năng gan, thận và huyết học trong quá trình điều trị.",
  "than": "",
  "luuy": "• Độc tính trên thận: tăng lên khi phối hợp với piperacillin/tazobactam, aminoglycosid, amphotericin B, colistin, polymyxin B, cisplatin. Hạn chế phối hợp, nhất là ở người bệnh đã suy thận từ trước.\n• Độc tính trên tai.\n• Hội chứng truyền vancomycin (trước đây gọi là hội chứng người đỏ): đỏ bừng, ban dát sần vùng mặt cổ, hạ huyết áp khi truyền nhanh. Dự phòng bằng cách pha loãng và giữ tốc độ truyền không quá 10 mg/phút, luân phiên vị trí truyền.\n• Cần giám sát nồng độ thuốc trong máu để hiệu chỉnh liều duy trì.",
  "tuongtac": "",
  "pha": "",
  "nguon": "Tổng hợp từ Dược thư Quốc gia Việt Nam 2022, Hướng dẫn sử dụng kháng sinh của Bộ Y tế (QĐ 708/QĐ-BYT) và tờ hướng dẫn sử dụng của nhà sản xuất, qua các bản tổng hợp đăng công khai. CHƯA đối chiếu trực tiếp với bản gốc.",
  "soat": false
 },
 {
  "ten": "Teicoplanin",
  "cls": "Kháng khuẩn khác",
  "nhom": "Nhóm thuốc kháng khuẩn khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Colistin",
  "cls": "Kháng khuẩn khác",
  "nhom": "Nhóm thuốc kháng khuẩn khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Metronidazol",
  "cls": "Kháng khuẩn khác",
  "nhom": "Nhóm thuốc kháng khuẩn khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Tinidazol",
  "cls": "Kháng khuẩn khác",
  "nhom": "Nhóm thuốc kháng khuẩn khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Fosfomycin",
  "cls": "Kháng khuẩn khác",
  "nhom": "Nhóm thuốc kháng khuẩn khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Linezolid",
  "cls": "Kháng khuẩn khác",
  "nhom": "Nhóm thuốc kháng khuẩn khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Daptomycin",
  "cls": "Kháng khuẩn khác",
  "nhom": "Nhóm thuốc kháng khuẩn khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Amphotericin B deoxycholat",
  "cls": "Kháng nấm",
  "nhom": "Nhóm kháng sinh chống nấm",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Amphotericin B phức hợp lipid",
  "cls": "Kháng nấm",
  "nhom": "Nhóm kháng sinh chống nấm",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Fluconazol",
  "cls": "Kháng nấm",
  "nhom": "Nhóm azol chống nấm",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Itraconazol",
  "cls": "Kháng nấm",
  "nhom": "Nhóm azol chống nấm",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Voriconazol",
  "cls": "Kháng nấm",
  "nhom": "Nhóm azol chống nấm",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Posaconazol",
  "cls": "Kháng nấm",
  "nhom": "Nhóm azol chống nấm",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Caspofungin",
  "cls": "Kháng nấm",
  "nhom": "Nhóm chống nấm khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 },
 {
  "ten": "Micafungin",
  "cls": "Kháng nấm",
  "nhom": "Nhóm chống nấm khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false
 }
];
