/* Thông tin thuốc — biên soạn nội bộ khoa Dược, Bệnh viện Đại học Phenikaa.
   KHÔNG phải văn bản đã ban hành. Tệp do màn hình Biên tập sinh ra. */

const DATA_VERSION = "2026-08-18";

/* Link sang ứng dụng Liều kháng sinh. Sửa nếu tên kho GitHub khác. */
const LINK_LIEU = "https://phenikaamecdls-code.github.io/lieu-khang-sinh/";

const INFO = [
 {
  "ten": "Doxycyclin",
  "cls": "Tetracyclin",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Tetracyclin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Tigecyclin",
  "cls": "Tetracyclin",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Tetracyclin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Ampicillin",
  "cls": "Penicillin",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Penicillin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Ampicillin/Sulbactam",
  "cls": "Penicillin",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Penicillin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Amoxicillin",
  "cls": "Penicillin",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Penicillin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Amoxicillin/Clavulanate",
  "cls": "Penicillin",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Penicillin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Cloxacillin",
  "cls": "Penicillin",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Penicillin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Ticarcillin/Clavulanate",
  "cls": "Penicillin",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Penicillin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Piperacillin/Tazobactam",
  "cls": "Penicillin",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Penicillin",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Cefalexin",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 1",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Cefazolin",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 1",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Cefoxitin",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 2",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Cefuroxim",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 2",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Cefaclor",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 2",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Cefprozil",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 2",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Cefotaxim",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Ceftazidim",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Ceftriaxon",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Cefixim",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Cefoperazon",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Cefoperazon/Sulbactam",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Cefpodoxim",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Ceftibuten",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Cefdinir",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Cefditoren",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Ceftazidim/Avibactam",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 3",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Cefepim",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 4",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Ceftolozan/Tazobactam",
  "cls": "Cephalosporin",
  "he": "Kháng khuẩn",
  "nhom": "Cephalosporin thế hệ 5",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Aztreonam",
  "cls": "Monobactam",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Monobactams",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Meropenem",
  "cls": "Carbapenem",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Carbapenem",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Imipenem/Cilastatin",
  "cls": "Carbapenem",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Carbapenem",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Ertapenem",
  "cls": "Carbapenem",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Carbapenem",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Doripenem",
  "cls": "Carbapenem",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Carbapenem",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Sulfamethoxazol/Trimethoprim",
  "cls": "Sulfonamid",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Sulfonamid và trimethoprim",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Azithromycin",
  "cls": "Macrolid",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Macrolid",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Clindamycin",
  "cls": "Macrolid",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Macrolid",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Clarithromycin",
  "cls": "Macrolid",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Macrolid",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Tobramycin",
  "cls": "Aminoglycosid",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Aminoglycosid",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Gentamycin",
  "cls": "Aminoglycosid",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Aminoglycosid",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Amikacin",
  "cls": "Aminoglycosid",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Aminoglycosid",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Ofloxacin",
  "cls": "Quinolon",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Quinolon",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Norfloxacin",
  "cls": "Quinolon",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Quinolon",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Ciprofloxacin",
  "cls": "Quinolon",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Quinolon",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Levofloxacin",
  "cls": "Quinolon",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Quinolon",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Moxifloxacin",
  "cls": "Quinolon",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm Quinolon",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Vancomycin",
  "cls": "Kháng khuẩn khác",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm thuốc kháng khuẩn khác",
  "coche": "Kháng sinh glycopeptid thế hệ 1, có tác dụng diệt khuẩn. Thuốc gắn vào đầu tận D-alanyl-D-alanin của các tiểu đơn vị peptid trong quá trình tạo peptidoglycan, qua đó chặn tổng hợp vách tế bào vi khuẩn; ngoài ra còn ức chế tổng hợp RNA của vi khuẩn.\nDo đích tác dụng khác với beta-lactam nên không xảy ra kháng chéo giữa hai nhóm.",
  "chidinh": "Phổ tác dụng giới hạn ở vi khuẩn Gram dương: S. aureus kể cả chủng kháng methicillin, S. epidermidis, liên cầu, cầu khuẩn ruột, phần lớn Actinomyces và Clostridium.\n\nĐường tĩnh mạch — nhiễm khuẩn nặng nghi ngờ hoặc xác định do Gram dương kháng methicillin: nhiễm khuẩn huyết, viêm nội tâm mạc, nhiễm khuẩn da và mô mềm, xương khớp, viêm phổi, viêm màng não.\n\nĐường uống — chỉ dùng cho viêm đại tràng giả mạc và tiêu chảy do Clostridioides difficile, vì thuốc gần như không hấp thu qua đường tiêu hoá. Không dùng đường uống để điều trị nhiễm khuẩn toàn thân.",
  "chongchidinh": "",
  "gan": "Vancomycin thải trừ chủ yếu qua thận ở dạng không đổi, nên các tài liệu tham khảo không đưa ra khuyến cáo hiệu chỉnh liều theo mức độ suy gan.\nVẫn cần theo dõi định kỳ chức năng gan, thận và huyết học trong quá trình điều trị.",
  "than": "",
  "luuy": "• Độc tính trên thận: tăng lên khi phối hợp với piperacillin/tazobactam, aminoglycosid, amphotericin B, colistin, polymyxin B, cisplatin. Hạn chế phối hợp, nhất là ở người bệnh đã suy thận từ trước.\n• Độc tính trên tai.\n• Hội chứng truyền vancomycin (trước đây gọi là hội chứng người đỏ): đỏ bừng, ban dát sần vùng mặt cổ, hạ huyết áp khi truyền nhanh. Dự phòng bằng cách pha loãng và giữ tốc độ truyền không quá 10 mg/phút, luân phiên vị trí truyền.\n• Cần giám sát nồng độ thuốc trong máu để hiệu chỉnh liều duy trì.",
  "tuongtac": "",
  "pha": "",
  "nguon": "Tổng hợp từ Dược thư Quốc gia Việt Nam 2022, Hướng dẫn sử dụng kháng sinh của Bộ Y tế (QĐ 708/QĐ-BYT) và tờ hướng dẫn sử dụng của nhà sản xuất, qua các bản tổng hợp đăng công khai. CHƯA đối chiếu trực tiếp với bản gốc.",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Teicoplanin",
  "cls": "Kháng khuẩn khác",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm thuốc kháng khuẩn khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Colistin",
  "cls": "Kháng khuẩn khác",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm thuốc kháng khuẩn khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Metronidazol",
  "cls": "Kháng khuẩn khác",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm thuốc kháng khuẩn khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Tinidazol",
  "cls": "Kháng khuẩn khác",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm thuốc kháng khuẩn khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Fosfomycin",
  "cls": "Kháng khuẩn khác",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm thuốc kháng khuẩn khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Linezolid",
  "cls": "Kháng khuẩn khác",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm thuốc kháng khuẩn khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Daptomycin",
  "cls": "Kháng khuẩn khác",
  "he": "Kháng khuẩn",
  "nhom": "Nhóm thuốc kháng khuẩn khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Amphotericin B deoxycholat",
  "cls": "Kháng nấm",
  "he": "Kháng nấm, kháng virus",
  "nhom": "Nhóm kháng sinh chống nấm",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Amphotericin B phức hợp lipid",
  "cls": "Kháng nấm",
  "he": "Kháng nấm, kháng virus",
  "nhom": "Nhóm kháng sinh chống nấm",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Fluconazol",
  "cls": "Kháng nấm",
  "he": "Kháng nấm, kháng virus",
  "nhom": "Nhóm azol chống nấm",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Itraconazol",
  "cls": "Kháng nấm",
  "he": "Kháng nấm, kháng virus",
  "nhom": "Nhóm azol chống nấm",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Voriconazol",
  "cls": "Kháng nấm",
  "he": "Kháng nấm, kháng virus",
  "nhom": "Nhóm azol chống nấm",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Posaconazol",
  "cls": "Kháng nấm",
  "he": "Kháng nấm, kháng virus",
  "nhom": "Nhóm azol chống nấm",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Caspofungin",
  "cls": "Kháng nấm",
  "he": "Kháng nấm, kháng virus",
  "nhom": "Nhóm chống nấm khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Micafungin",
  "cls": "Kháng nấm",
  "he": "Kháng nấm, kháng virus",
  "nhom": "Nhóm chống nấm khác",
  "coche": "",
  "chidinh": "",
  "chongchidinh": "",
  "gan": "",
  "than": "",
  "luuy": "",
  "tuongtac": "",
  "pha": "",
  "nguon": "",
  "soat": false,
  "lieu": "",
  "xemlieu": true
 },
 {
  "ten": "Cilostazol",
  "cls": "Ức chế kết tập tiểu cầu",
  "he": "Máu và đông máu",
  "nhom": "Thuốc chống huyết khối",
  "xemlieu": false,
  "coche": "Ức chế chọn lọc phosphodiesterase III, làm tăng cAMP trong tiểu cầu và cơ trơn thành mạch — vừa ức chế kết tập tiểu cầu vừa giãn mạch. Chuyển hóa qua CYP3A4 và CYP2C19.",
  "chidinh": "Đau cách hồi ở chân do bệnh động mạch ngoại vi giai đoạn II Fontaine. Chỉ dùng hàng thứ hai, sau khi ngừng thuốc lá và tập luyện có giám sát vẫn không cải thiện.",
  "chongchidinh": "Suy tim sung huyết, mọi mức độ.\nCrCl ≤ 25 mL/phút. Suy gan trung bình hoặc nặng.\nĐang dùng từ 2 thuốc chống kết tập tiểu cầu hoặc chống đông trở lên.\nCơ địa chảy máu: loét dạ dày tiến triển, đột quỵ xuất huyết trong 6 tháng, võng mạc tăng sinh do đái tháo đường, tăng huyết áp chưa kiểm soát.\nTiền sử loạn nhịp thất, QT kéo dài. Nhồi máu cơ tim hoặc can thiệp mạch vành trong 6 tháng. Có thai.",
  "lieu": "100 mg × 2 lần/ngày.\nUống trước bữa sáng và bữa tối 30 phút, hoặc sau ăn 2 giờ — uống cùng thức ăn làm tăng nồng độ đỉnh.\nGiảm còn 50 mg × 2 lần/ngày khi dùng cùng omeprazol, azol, macrolid hoặc thuốc ức chế protease.\nĐánh giá lại sau 3 tháng, không cải thiện thì ngừng.",
  "gan": "Nhẹ: không chỉnh liều. Trung bình đến nặng: chống chỉ định.",
  "than": "CrCl > 25 mL/phút: không chỉnh liều. CrCl ≤ 25 mL/phút: chống chỉ định.",
  "luuy": "Đau đầu rất hay gặp và là lý do bỏ thuốc số một. Báo trước cho người bệnh, thường đỡ dần sau 2–4 tuần.\nTác dụng xuất hiện chậm, cần 2–4 tuần, tối đa tới 12 tuần. Đừng kết luận thất bại quá sớm.\nNgừng 5 ngày trước phẫu thuật theo chương trình, kể cả nhổ răng.\nNgừng ngay nếu xuất huyết võng mạc, hoặc có sốt và dấu hiệu giảm bạch cầu, giảm tiểu cầu.",
  "tuongtac": "Omeprazol, azol, macrolid, ức chế protease: giảm nửa liều. Cặp với omeprazol rất dễ bỏ sót vì thuốc ức chế bơm proton hay được kê kèm mặc định.\nDiltiazem: tăng AUC khoảng 40%.\nThuốc chống đông và chống kết tập tiểu cầu khác: phối hợp từ 2 thuốc trở lên là chống chỉ định.",
  "pha": "",
  "nguon": "Dược thư Quốc gia Việt Nam 2022, chuyên luận Cilostazol, ATC B01AC23. Tờ HDSD Nibixada, SĐK VN-21095-18.\nhttps://pharmog.com/wp/cilostazol-nibixada/\nhttps://trungtamthuoc.com/hoat-chat/cilostazol",
  "soat": false
 }
];
