/* Dịch truyền dinh dưỡng — chép từ Điểm tin Thông tin thuốc số 3/2025,
   khoa Dược Bệnh viện Đại học Phenikaa. Danh mục chế phẩm hiện có tại bệnh viện.
   Số liệu giữ nguyên theo bản tin. Tốc độ mL/giờ do app tự tính từ cân nặng. */

const DT_VERSION = "2026-08-20";

/* rate.kieu: "kg"   -> mL/kg/giờ, app nhân với cân nặng
              "gio"  -> mL/giờ cố định
              "phut" -> mL/phút, app đổi ra mL/giờ
   duong: "ngoaivi" = ngoại vi hoặc trung tâm | "trungtam" = bắt buộc trung tâm */

const DICHTRUYEN = [
 /* ---------- Nhũ dịch lipid ---------- */
 {
  "id": "smoflipid-20",
  "nhom": "Nhũ dịch lipid",
  "ten": "Smoflipid 20%",
  "dong": "Chai 250 mL",
  "vols": [250],
  "dang": "Nhũ tương truyền tĩnh mạch",
  "hang": "Fresenius Kabi Austria GmbH, Áo",
  "hoatchat": "Lipid",
  "nongdo": "Lipid 20%",
  "duong": "ngoaivi",
  "osm": "380 mOsm/kg",
  "rate": { "kieu": "kg", "kc": 0.63, "max": 0.75 },
  "tocTxt": "Người lớn — khuyến cáo 0,63 mL/kg/giờ, tối đa 0,75 mL/kg/giờ",
  "thoigian": "",
  "luuy": []
 },
 {
  "id": "lipofundin-10",
  "nhom": "Nhũ dịch lipid",
  "ten": "Lipofundin MCT/LCT 10%",
  "dong": "Chai 250 mL",
  "vols": [250],
  "dang": "Nhũ tương tiêm truyền",
  "hang": "B. Braun Melsungen AG, Đức",
  "hoatchat": "Lipid",
  "nongdo": "Lipid 10%",
  "duong": "trungtam",
  "osm": "345 mOsm/L",
  "rate": { "kieu": "kg", "max": 1.5 },
  "tocTxt": "Người lớn — tối đa 1,5 mL/kg/giờ",
  "thoigian": "",
  "luuy": ["Trong 15 phút đầu, truyền bằng 50% tốc độ tối đa."]
 },
 {
  "id": "lipofundin-20",
  "nhom": "Nhũ dịch lipid",
  "ten": "Lipofundin MCT/LCT 20%",
  "dong": "Chai 100 mL và chai 250 mL",
  "vols": [100, 250],
  "dang": "Nhũ tương tiêm truyền",
  "hang": "B. Braun Melsungen AG, Đức",
  "hoatchat": "Lipid",
  "nongdo": "Lipid 20%",
  "duong": "trungtam",
  "osm": "380 mOsm/L",
  "rate": { "kieu": "kg", "max": 0.75 },
  "tocTxt": "Người lớn — tối đa 0,75 mL/kg/giờ",
  "thoigian": "",
  "luuy": ["Trong 15 phút đầu, truyền bằng 50% tốc độ tối đa."]
 },

 /* ---------- Acid amin thường và hỗn hợp cơ bản ---------- */
 {
  "id": "aminoplasmal-10",
  "nhom": "Acid amin thường và hỗn hợp cơ bản",
  "ten": "Aminoplasmal B.Braun 10% E",
  "dong": "Chai 500 mL",
  "vols": [500],
  "dang": "Nhũ tương tiêm truyền",
  "hang": "B. Braun Melsungen AG, Đức",
  "hoatchat": "Acid amin + điện giải",
  "nongdo": "Acid amin 10%",
  "duong": "trungtam",
  "osm": "1021 mOsm/L",
  "rate": { "kieu": "kg", "max": 1 },
  "tocTxt": "1 mL/kg/giờ",
  "thoigian": "",
  "luuy": ["Áp suất thẩm thấu 1021 mOsm/L — bắt buộc truyền tĩnh mạch trung tâm."]
 },
 {
  "id": "aminoplasmal-5",
  "nhom": "Acid amin thường và hỗn hợp cơ bản",
  "ten": "Aminoplasmal B.Braun 5% E",
  "dong": "Chai 500 mL",
  "vols": [500],
  "dang": "Nhũ tương tiêm truyền",
  "hang": "B. Braun Melsungen AG, Đức",
  "hoatchat": "Acid amin + điện giải",
  "nongdo": "Acid amin 5%",
  "duong": "trungtam",
  "osm": "592 mOsm/L",
  "rate": { "kieu": "kg", "max": 2 },
  "tocTxt": "Tối đa 2 mL/kg/giờ — tương đương 140 mL/giờ cho bệnh nhân 70 kg",
  "thoigian": "",
  "luuy": []
 },
 {
  "id": "aminomix-peripheral",
  "nhom": "Acid amin thường và hỗn hợp cơ bản",
  "ten": "Aminomix Peripheral",
  "dong": "Túi 1000 mL",
  "vols": [1000],
  "dang": "Dung dịch tiêm truyền",
  "hang": "Fresenius Kabi Austria GmbH, Áo",
  "hoatchat": "Acid amin + glucose + điện giải",
  "nongdo": "Acid amin 7% · Glucose 12,6%",
  "duong": "ngoaivi",
  "osm": "770 mOsm/L",
  "rate": { "kieu": "kg", "max": 2.9 },
  "tocTxt": "2,9 mL/kg/giờ",
  "thoigian": "",
  "luuy": []
 },
 {
  "id": "nutriflex-peri",
  "nhom": "Acid amin thường và hỗn hợp cơ bản",
  "ten": "Nutriflex peri",
  "dong": "Túi 1000 mL",
  "vols": [1000],
  "dang": "Dung dịch tiêm truyền",
  "hang": "B. Braun Medical AG, Thụy Sĩ",
  "hoatchat": "Acid amin + glucose + điện giải",
  "nongdo": "Acid amin 4% · Glucose 8%",
  "duong": "ngoaivi",
  "osm": "900 mOsm/L",
  "rate": { "kieu": "kg", "max": 2.5 },
  "tocTxt": "2,5 mL/kg/giờ",
  "thoigian": "",
  "luuy": []
 },

 /* ---------- Acid amin đặc hiệu ---------- */
 {
  "id": "nephrosteril-7",
  "nhom": "Acid amin đặc hiệu (gan, thận, nhi khoa)",
  "ten": "Nephrosteril 7%",
  "dong": "Chai 250 mL",
  "vols": [250],
  "dang": "Dung dịch tiêm truyền",
  "hang": "Fresenius Kabi Austria GmbH, Áo",
  "hoatchat": "Acid amin",
  "nongdo": "Acid amin 7%",
  "duong": "trungtam",
  "osm": "645 mOsm/L",
  "rate": { "kieu": "gio", "max": 60 },
  "tocTxt": "Tối đa 60 mL/giờ",
  "thoigian": "",
  "luuy": ["Công thức acid amin dành cho bệnh nhân suy thận."]
 },
 {
  "id": "aminosteril-n-hepa-8",
  "nhom": "Acid amin đặc hiệu (gan, thận, nhi khoa)",
  "ten": "Aminosteril N-hepa 8%",
  "dong": "Chai 250 mL",
  "vols": [250],
  "dang": "Dung dịch tiêm truyền",
  "hang": "Fresenius Kabi Austria GmbH, Áo",
  "hoatchat": "Acid amin",
  "nongdo": "Acid amin 8%",
  "duong": "ngoaivi",
  "osm": "770 mOsm/L",
  "rate": { "kieu": "kg", "kc": 1.0, "max": 1.25 },
  "tocTxt": "Khuyến cáo 1,0–1,25 mL/kg/giờ, tối đa 1,25 mL/kg/giờ",
  "thoigian": "",
  "luuy": ["Công thức acid amin dành cho bệnh nhân bệnh gan."]
 },
 {
  "id": "aminoleban",
  "nhom": "Acid amin đặc hiệu (gan, thận, nhi khoa)",
  "ten": "Aminoleban",
  "dong": "Túi 200 mL",
  "vols": [200],
  "dang": "Dung dịch truyền tĩnh mạch",
  "hang": "Công ty Cổ phần Dược phẩm Otsuka Việt Nam",
  "hoatchat": "Acid amin",
  "nongdo": "Acid amin 8%",
  "duong": "ngoaivi",
  "osm": "",
  "rate": { "kieu": "phut", "min": 1.7, "max": 2.8 },
  "tocTxt": "Tốc độ thông thường 1,7–2,8 mL/phút",
  "thoigian": "",
  "luuy": ["Công thức acid amin dành cho bệnh nhân bệnh gan.",
           "Bản tin ghi tốc độ theo mL/phút, khác đơn vị với các chế phẩm còn lại — đối chiếu tờ hướng dẫn trước khi cài bơm."]
 },
 {
  "id": "morihepamin",
  "nhom": "Acid amin đặc hiệu (gan, thận, nhi khoa)",
  "ten": "Morihepamin",
  "dong": "Túi 200 mL",
  "vols": [200],
  "dang": "Dung dịch truyền tĩnh mạch",
  "hang": "Ay Pharmaceuticals Co., LTD, Nhật Bản",
  "hoatchat": "Acid amin",
  "nongdo": "Acid amin 7,6%",
  "duong": "trungtam",
  "osm": "",
  "rate": { "kieu": "gio", "max": 166 },
  "tocTxt": "Tối đa 166 mL/giờ",
  "thoigian": "Tối thiểu 180 phút cho 500 mL",
  "luuy": ["Công thức acid amin dành cho bệnh nhân bệnh gan.",
           "Bản tin ghi thời gian tối thiểu cho thể tích 500 mL, trong khi túi tại bệnh viện là 200 mL — kiểm tra lại khi áp dụng."]
 },
 {
  "id": "vaminolact",
  "nhom": "Acid amin đặc hiệu (gan, thận, nhi khoa)",
  "ten": "Vaminolact",
  "dong": "Chai 100 mL",
  "vols": [100],
  "dang": "Dung dịch truyền tĩnh mạch",
  "hang": "Fresenius Kabi Austria GmbH, Áo",
  "hoatchat": "Acid amin",
  "nongdo": "Acid amin 6,5%",
  "duong": "ngoaivi",
  "osm": "510 mOsm/kg nước",
  "rate": { "kieu": "gio", "max": 12.5 },
  "tocTxt": "Tối đa 12,5 mL/giờ",
  "thoigian": "Tối thiểu 8 giờ cho 100 mL. Nên truyền liên tục trong 24 giờ.",
  "luuy": ["Công thức acid amin dành cho nhi khoa."]
 },

 /* ---------- Dung dịch nuôi dưỡng toàn phần ---------- */
 {
  "id": "smofkabiven-peripheral",
  "nhom": "Dung dịch nuôi dưỡng toàn phần",
  "ten": "Smofkabiven Peripheral",
  "dong": "Túi 1206 mL",
  "vols": [1206],
  "dang": "Nhũ tương tiêm truyền",
  "hang": "Fresenius Kabi AB, Thụy Điển",
  "hoatchat": "Acid amin + glucose + lipid + điện giải",
  "nongdo": "Acid amin 3,2% · Glucose 7% · Lipid 2,8%",
  "duong": "ngoaivi",
  "osm": "850 mOsm/L",
  "rate": { "kieu": "kg", "max": 3.0 },
  "tocTxt": "Tối đa 3,0 mL/kg/giờ",
  "thoigian": "Người lớn 14–24 giờ. Trẻ em 12–24 giờ.",
  "luuy": []
 },
 {
  "id": "periolimel-n4e",
  "nhom": "Dung dịch nuôi dưỡng toàn phần",
  "ten": "Periolimel N4E",
  "dong": "Túi 1000 mL",
  "vols": [1000],
  "dang": "Nhũ dịch truyền tĩnh mạch",
  "hang": "Baxter S.A, Bỉ",
  "hoatchat": "Acid amin + glucose + lipid + điện giải",
  "nongdo": "Acid amin 2,5% · Glucose 7,5% · Lipid 3%",
  "duong": "ngoaivi",
  "osm": "760 mOsm/L",
  "rate": { "kieu": "gio", "min": 40, "max": 80 },
  "tocTxt": "40–80 mL/giờ",
  "thoigian": "12–24 giờ",
  "luuy": ["Không dùng chung đường truyền với ceftriaxon — nguy cơ kết tủa muối calci-ceftriaxon."]
 },
 {
  "id": "olimel-n9e",
  "nhom": "Dung dịch nuôi dưỡng toàn phần",
  "ten": "Olimel N9E",
  "dong": "Túi 1000 mL",
  "vols": [1000],
  "dang": "Nhũ dịch truyền tĩnh mạch",
  "hang": "Baxter S.A, Bỉ",
  "hoatchat": "Acid amin + glucose + lipid + điện giải",
  "nongdo": "Acid amin 5,7% · Glucose 6,9% · Lipid 4%",
  "duong": "trungtam",
  "osm": "1310 mOsm/L",
  "rate": { "kieu": "gio", "min": 40, "max": 80 },
  "tocTxt": "40–80 mL/giờ",
  "thoigian": "12–24 giờ",
  "luuy": ["Áp suất thẩm thấu 1310 mOsm/L — bắt buộc truyền tĩnh mạch trung tâm.",
           "Không dùng chung đường truyền với ceftriaxon — nguy cơ kết tủa muối calci-ceftriaxon."]
 }
];
